import type { Ui } from "./types";

export const ui: Ui = {
  mn: {
    brand: "~/tergel",
    langName: "Монгол",
    nav: {
      label: "Үндсэн цэс",
      about: "Тухай",
      skills: "Ур чадвар",
      experience: "Туршлага",
      projects: "Төслүүд",
      contact: "Холбоо барих",
      cv: "CV",
    },
    sections: {
      about: "Миний тухай",
      skills: "Ур чадвар",
      experience: "Ажлын туршлага",
      projects: "Төслүүд",
      work: "Ажлын төслүүд",
      personal: "Хувийн / OSS",
      contact: "Холбоо барих",
      education: "Боловсрол",
    },
    actions: {
      viewProjects: "Төслүүд харах",
      viewCv: "CV харах",
      contactMe: "Холбоо барих",
      live: "Live",
      source: "Код",
      print: "Хэвлэх / PDF",
    },
    hero: { prompt: "$ whoami" },
    about: { years: "Туршлага", yearsValue: "{n}+ жил" },
    contact: {
      body: "Шинэ төсөл, хамтын ажиллагаа, эсвэл зүгээр л мэндчилэх бол бичээрэй. Ихэвчлэн нэг өдрийн дотор хариулдаг.",
      email: "И-мэйл",
    },
    cv: {
      title: "CV",
      summary: "Товч танилцуулга",
      featuredProjects: "Гол төслүүд",
      present: "одоог хүртэл",
    },
    notFound: {
      title: "Хуудас олдсонгүй",
      body: "Ийм хаяг байхгүй эсвэл зөөгдсөн байна.",
      home: "Нүүр хуудас",
    },
    footer: { builtWith: "Next.js + Tailwind · GitHub Pages" },
  },
  en: {
    brand: "~/tergel",
    langName: "English",
    nav: {
      label: "Main navigation",
      about: "About",
      skills: "Skills",
      experience: "Experience",
      projects: "Projects",
      contact: "Contact",
      cv: "CV",
    },
    sections: {
      about: "About me",
      skills: "Skills",
      experience: "Work experience",
      projects: "Projects",
      work: "Work projects",
      personal: "Personal / OSS",
      contact: "Get in touch",
      education: "Education",
    },
    actions: {
      viewProjects: "View projects",
      viewCv: "View CV",
      contactMe: "Contact me",
      live: "Live",
      source: "Source",
      print: "Print / PDF",
    },
    hero: { prompt: "$ whoami" },
    about: { years: "Experience", yearsValue: "{n}+ years" },
    contact: {
      body: "Have a project, a collaboration idea, or just want to say hi? Write me. I usually reply within a day.",
      email: "Email",
    },
    cv: {
      title: "CV",
      summary: "Summary",
      featuredProjects: "Selected projects",
      present: "Present",
    },
    notFound: {
      title: "Page not found",
      body: "This address does not exist or has moved.",
      home: "Home",
    },
    footer: { builtWith: "Next.js + Tailwind · GitHub Pages" },
  },
};
